[
    {
       "state":"Wyoming",
       "stateAbbr":"WY",
       "allArtists":[
          {
             "count":"3,015",
             "lq":"0.68"
          }
       ],
       "architects":[
          {
             "count":"340",
             "lq":"1.04"
          }
       ],
       "artDirectors":[
          {
             "count":"365",
             "lq":"0.85"
          }
       ],
       "designers":[
          {
             "count":"1,135",
             "lq":"0.66"
          }
       ],
       "dancers":[
          {
             "count":"0",
             "lq":"0.00"
          }
       ],
       "musicians":[
          {
             "count":"135",
             "lq":"0.43"
          }
       ],
       "actors":[
          {
             "count":"55",
             "lq":"0.49"
          }
       ],
       "entertainers":[
          {
             "count":"*",
             "lq":"*"
          }
       ],
       "writers":[
          {
             "count":"335",
             "lq":"0.73"
          }
       ],
       "photographers":[
          {
             "count":"290",
             "lq":"0.83"
          }
       ]
    },
    {
       "state":"Wisconsin",
       "stateAbbr":"WI",
       "allArtists":[
          {
             "count":"37,095",
             "lq":"0.82"
          }
       ],
       "architects":[
          {
             "count":"2,300",
             "lq":"0.69"
          }
       ],
       "artDirectors":[
          {
             "count":"3,235",
             "lq":"0.74"
          }
       ],
       "designers":[
          {
             "count":"17,550",
             "lq":"1.00"
          }
       ],
       "dancers":[
          {
             "count":"260",
             "lq":"0.63"
          }
       ],
       "musicians":[
          {
             "count":"2,440",
             "lq":"0.77"
          }
       ],
       "actors":[
          {
             "count":"315",
             "lq":"0.28"
          }
       ],
       "entertainers":[
          {
             "count":"495",
             "lq":"0.54"
          }
       ],
       "writers":[
          {
             "count":"3,900",
             "lq":"0.84"
          }
       ],
       "photographers":[
          {
             "count":"2,590",
             "lq":"0.73"
          }
       ]
    },
    {
       "state":"West Virginia",
       "stateAbbr":"WV",
       "allArtists":[
          {
             "count":"6,140",
             "lq":"0.53"
          }
       ],
       "architects":[
          {
             "count":"160",
             "lq":"0.19"
          }
       ],
       "artDirectors":[
          {
             "count":"460",
             "lq":"0.41"
          }
       ],
       "designers":[
          {
             "count":"2,615",
             "lq":"0.58"
          }
       ],
       "dancers":[
          {
             "count":"90",
             "lq":"0.85"
          }
       ],
       "musicians":[
          {
             "count":"495",
             "lq":"0.61"
          }
       ],
       "actors":[
          {
             "count":"85",
             "lq":"0.29"
          }
       ],
       "entertainers":[
          {
             "count":"65",
             "lq":"0.28"
          }
       ],
       "writers":[
          {
             "count":"750",
             "lq":"0.63"
          }
       ],
       "photographers":[
          {
             "count":"615",
             "lq":"0.68"
          }
       ]
    },
    {
       "state":"Washington",
       "stateAbbr":"WA",
       "allArtists":[
          {
             "count":"61,160",
             "lq":"1.09"
          }
       ],
       "architects":[
          {
             "count":"6,120",
             "lq":"1.49"
          }
       ],
       "artDirectors":[
          {
             "count":"6,915",
             "lq":"1.28"
          }
       ],
       "designers":[
          {
             "count":"25,435",
             "lq":"1.17"
          }
       ],
       "dancers":[
          {
             "count":"615",
             "lq":"1.20"
          }
       ],
       "musicians":[
          {
             "count":"2,935",
             "lq":"0.75"
          }
       ],
       "actors":[
          {
             "count":"685",
             "lq":"0.49"
          }
       ],
       "entertainers":[
          {
             "count":"730",
             "lq":"0.64"
          }
       ],
       "writers":[
          {
             "count":"6,910",
             "lq":"1.20"
          }
       ],
       "photographers":[
          {
             "count":"4,410",
             "lq":"1.00"
          }
       ]
    },
    {
       "state":"Virginia",
       "stateAbbr":"VA",
       "allArtists":[
          {
             "count":"57,975",
             "lq":"0.89"
          }
       ],
       "architects":[
          {
             "count":"5,750",
             "lq":"1.20"
          }
       ],
       "artDirectors":[
          {
             "count":"4,505",
             "lq":"0.72"
          }
       ],
       "designers":[
          {
             "count":"22,045",
             "lq":"0.87"
          }
       ],
       "dancers":[
          {
             "count":"330",
             "lq":"0.55"
          }
       ],
       "musicians":[
          {
             "count":"4,745",
             "lq":"1.04"
          }
       ],
       "actors":[
          {
             "count":"580",
             "lq":"0.35"
          }
       ],
       "entertainers":[
          {
             "count":"590",
             "lq":"0.44"
          }
       ],
       "writers":[
          {
             "count":"7,870",
             "lq":"1.17"
          }
       ],
       "photographers":[
          {
             "count":"3,710",
             "lq":"0.72"
          }
       ]
    },
    {
       "state":"Vermont",
       "stateAbbr":"VT",
       "allArtists":[
          {
             "count":"5,835",
             "lq":"1.17"
          }
       ],
       "architects":[
          {
             "count":"415",
             "lq":"1.13"
          }
       ],
       "artDirectors":[
          {
             "count":"865",
             "lq":"1.80"
          }
       ],
       "designers":[
          {
             "count":"1,970",
             "lq":"1.02"
          }
       ],
       "dancers":[
          {
             "count":"*",
             "lq":"*"
          }
       ],
       "musicians":[
          {
             "count":"485",
             "lq":"1.39"
          }
       ],
       "actors":[
          {
             "count":"15",
             "lq":"0.12"
          }
       ],
       "entertainers":[
          {
             "count":"75",
             "lq":"0.74"
          }
       ],
       "writers":[
          {
             "count":"920",
             "lq":"1.79"
          }
       ],
       "photographers":[
          {
             "count":"465",
             "lq":"1.19"
          }
       ]
    },
    {
       "state":"Utah",
       "stateAbbr":"UT",
       "allArtists":[
          {
             "count":"24,410",
             "lq":"1.08"
          }
       ],
       "architects":[
          {
             "count":"1,340",
             "lq":"0.80"
          }
       ],
       "artDirectors":[
          {
             "count":"2,880",
             "lq":"1.32"
          }
       ],
       "designers":[
          {
             "count":"10,950",
             "lq":"1.24"
          }
       ],
       "dancers":[
          {
             "count":"120",
             "lq":"0.58"
          }
       ],
       "musicians":[
          {
             "count":"530",
             "lq":"0.33"
          }
       ],
       "actors":[
          {
             "count":"415",
             "lq":"0.72"
          }
       ],
       "entertainers":[
          {
             "count":"300",
             "lq":"0.65"
          }
       ],
       "writers":[
          {
             "count":"2,760",
             "lq":"1.18"
          }
       ],
       "photographers":[
          {
             "count":"2,685",
             "lq":"1.50"
          }
       ]
    },
    {
       "state":"Texas",
       "stateAbbr":"TX",
       "allArtists":[
          {
             "count":"166,210",
             "lq":"0.81"
          }
       ],
       "architects":[
          {
             "count":"14,575",
             "lq":"0.97"
          }
       ],
       "artDirectors":[
          {
             "count":"15,535",
             "lq":"0.79"
          }
       ],
       "designers":[
          {
             "count":"68,305",
             "lq":"0.86"
          }
       ],
       "dancers":[
          {
             "count":"1,435",
             "lq":"0.77"
          }
       ],
       "musicians":[
          {
             "count":"13,100",
             "lq":"0.92"
          }
       ],
       "actors":[
          {
             "count":"1,830",
             "lq":"0.35"
          }
       ],
       "entertainers":[
          {
             "count":"2,995",
             "lq":"0.72"
          }
       ],
       "writers":[
          {
             "count":"14,035",
             "lq":"0.66"
          }
       ],
       "photographers":[
          {
             "count":"15,500",
             "lq":"0.96"
          }
       ]
    },
    {
       "state":"Tennessee",
       "stateAbbr":"TN",
       "allArtists":[
          {
             "count":"43,395",
             "lq":"0.90"
          }
       ],
       "architects":[
          {
             "count":"1,815",
             "lq":"0.51"
          }
       ],
       "artDirectors":[
          {
             "count":"3,300",
             "lq":"0.71"
          }
       ],
       "designers":[
          {
             "count":"14,430",
             "lq":"0.77"
          }
       ],
       "dancers":[
          {
             "count":"365",
             "lq":"0.83"
          }
       ],
       "musicians":[
          {
             "count":"8,360",
             "lq":"2.49"
          }
       ],
       "actors":[
          {
             "count":"400",
             "lq":"0.33"
          }
       ],
       "entertainers":[
          {
             "count":"805",
             "lq":"0.82"
          }
       ],
       "writers":[
          {
             "count":"3,420",
             "lq":"0.69"
          }
       ],
       "photographers":[
          {
             "count":"3,810",
             "lq":"1.01"
          }
       ]
    },
    {
       "state":"South Dakota",
       "stateAbbr":"SD",
       "allArtists":[
          {
             "count":"4,200",
             "lq":"0.62"
          }
       ],
       "architects":[
          {
             "count":"195",
             "lq":"0.39"
          }
       ],
       "artDirectors":[
          {
             "count":"425",
             "lq":"0.65"
          }
       ],
       "designers":[
          {
             "count":"1,980",
             "lq":"0.76"
          }
       ],
       "dancers":[
          {
             "count":"40",
             "lq":"0.65"
          }
       ],
       "musicians":[
          {
             "count":"190",
             "lq":"0.40"
          }
       ],
       "actors":[
          {
             "count":"15",
             "lq":"0.09"
          }
       ],
       "entertainers":[
          {
             "count":"30",
             "lq":"0.22"
          }
       ],
       "writers":[
          {
             "count":"405",
             "lq":"0.58"
          }
       ],
       "photographers":[
          {
             "count":"360",
             "lq":"0.68"
          }
       ]
    },
    {
       "state":"South Carolina",
       "stateAbbr":"SC",
       "allArtists":[
          {
             "count":"25,125",
             "lq":"0.70"
          }
       ],
       "architects":[
          {
             "count":"1,860",
             "lq":"0.71"
          }
       ],
       "artDirectors":[
          {
             "count":"2,130",
             "lq":"0.62"
          }
       ],
       "designers":[
          {
             "count":"10,280",
             "lq":"0.74"
          }
       ],
       "dancers":[
          {
             "count":"190",
             "lq":"0.58"
          }
       ],
       "musicians":[
          {
             "count":"2,470",
             "lq":"0.99"
          }
       ],
       "actors":[
          {
             "count":"255",
             "lq":"0.28"
          }
       ],
       "entertainers":[
          {
             "count":"240",
             "lq":"0.33"
          }
       ],
       "writers":[
          {
             "count":"2,490",
             "lq":"0.68"
          }
       ],
       "photographers":[
          {
             "count":"2,025",
             "lq":"0.72"
          }
       ]
    },
    {
       "state":"Rhode Island",
       "stateAbbr":"RI",
       "allArtists":[
          {
             "count":"8,615",
             "lq":"1.04"
          }
       ],
       "architects":[
          {
             "count":"585",
             "lq":"0.96"
          }
       ],
       "artDirectors":[
          {
             "count":"730",
             "lq":"0.91"
          }
       ],
       "designers":[
          {
             "count":"3,905",
             "lq":"1.22"
          }
       ],
       "dancers":[
          {
             "count":"65",
             "lq":"0.86"
          }
       ],
       "musicians":[
          {
             "count":"315",
             "lq":"0.54"
          }
       ],
       "actors":[
          {
             "count":"125",
             "lq":"0.60"
          }
       ],
       "entertainers":[
          {
             "count":"85",
             "lq":"0.50"
          }
       ],
       "writers":[
          {
             "count":"965",
             "lq":"1.13"
          }
       ],
       "photographers":[
          {
             "count":"800",
             "lq":"1.23"
          }
       ]
    },
    {
       "state":"Pennsylvania",
       "stateAbbr":"PA",
       "allArtists":[
          {
             "count":"79,425",
             "lq":"0.83"
          }
       ],
       "architects":[
          {
             "count":"5,985",
             "lq":"0.85"
          }
       ],
       "artDirectors":[
          {
             "count":"7,390",
             "lq":"0.80"
          }
       ],
       "designers":[
          {
             "count":"30,975",
             "lq":"0.84"
          }
       ],
       "dancers":[
          {
             "count":"590",
             "lq":"0.67"
          }
       ],
       "musicians":[
          {
             "count":"6,065",
             "lq":"0.91"
          }
       ],
       "actors":[
          {
             "count":"1,465",
             "lq":"0.61"
          }
       ],
       "entertainers":[
          {
             "count":"1,495",
             "lq":"0.77"
          }
       ],
       "writers":[
          {
             "count":"8,710",
             "lq":"0.88"
          }
       ],
       "photographers":[
          {
             "count":"6,995",
             "lq":"0.93"
          }
       ]
    },
    {
       "state":"Oregon",
       "stateAbbr":"OR",
       "allArtists":[
          {
             "count":"37,905",
             "lq":"1.24"
          }
       ],
       "architects":[
          {
             "count":"3,025",
             "lq":"1.34"
          }
       ],
       "artDirectors":[
          {
             "count":"4,740",
             "lq":"1.61"
          }
       ],
       "designers":[
          {
             "count":"14,670",
             "lq":"1.24"
          }
       ],
       "dancers":[
          {
             "count":"495",
             "lq":"1.77"
          }
       ],
       "musicians":[
          {
             "count":"1,980",
             "lq":"0.93"
          }
       ],
       "actors":[
          {
             "count":"625",
             "lq":"0.81"
          }
       ],
       "entertainers":[
          {
             "count":"510",
             "lq":"0.82"
          }
       ],
       "writers":[
          {
             "count":"5,330",
             "lq":"1.69"
          }
       ],
       "photographers":[
          {
             "count":"2,965",
             "lq":"1.23"
          }
       ]
    },
    {
       "state":"Oklahoma",
       "stateAbbr":"OK",
       "allArtists":[
          {
             "count":"17,065",
             "lq":"0.62"
          }
       ],
       "architects":[
          {
             "count":"1,190",
             "lq":"0.59"
          }
       ],
       "artDirectors":[
          {
             "count":"1,880",
             "lq":"0.71"
          }
       ],
       "designers":[
          {
             "count":"6,585",
             "lq":"0.62"
          }
       ],
       "dancers":[
          {
             "count":"320",
             "lq":"1.27"
          }
       ],
       "musicians":[
          {
             "count":"1,430",
             "lq":"0.74"
          }
       ],
       "actors":[
          {
             "count":"150",
             "lq":"0.22"
          }
       ],
       "entertainers":[
          {
             "count":"335",
             "lq":"0.60"
          }
       ],
       "writers":[
          {
             "count":"1,485",
             "lq":"0.52"
          }
       ],
       "photographers":[
          {
             "count":"1,610",
             "lq":"0.74"
          }
       ]
    },
    {
       "state":"Ohio",
       "stateAbbr":"OH",
       "allArtists":[
          {
             "count":"64,760",
             "lq":"0.75"
          }
       ],
       "architects":[
          {
             "count":"4,170",
             "lq":"0.66"
          }
       ],
       "artDirectors":[
          {
             "count":"6,675",
             "lq":"0.80"
          }
       ],
       "designers":[
          {
             "count":"28,680",
             "lq":"0.86"
          }
       ],
       "dancers":[
          {
             "count":"795",
             "lq":"1.01"
          }
       ],
       "musicians":[
          {
             "count":"5,145",
             "lq":"0.85"
          }
       ],
       "actors":[
          {
             "count":"570",
             "lq":"0.26"
          }
       ],
       "entertainers":[
          {
             "count":"925",
             "lq":"0.53"
          }
       ],
       "writers":[
          {
             "count":"6,000",
             "lq":"0.67"
          }
       ],
       "photographers":[
          {
             "count":"4,975",
             "lq":"0.73"
          }
       ]
    },
    {
       "state":"North Dakota",
       "stateAbbr":"ND",
       "allArtists":[
          {
             "count":"3,330",
             "lq":"0.54"
          }
       ],
       "architects":[
          {
             "count":"325",
             "lq":"0.72"
          }
       ],
       "artDirectors":[
          {
             "count":"145",
             "lq":"0.25"
          }
       ],
       "designers":[
          {
             "count":"1,515",
             "lq":"0.64"
          }
       ],
       "dancers":[
          {
             "count":"*",
             "lq":"*"
          }
       ],
       "musicians":[
          {
             "count":"180",
             "lq":"0.42"
          }
       ],
       "actors":[
          {
             "count":"*",
             "lq":"*"
          }
       ],
       "entertainers":[
          {
             "count":"*",
             "lq":"*"
          }
       ],
       "writers":[
          {
             "count":"345",
             "lq":"0.54"
          }
       ],
       "photographers":[
          {
             "count":"370",
             "lq":"0.77"
          }
       ]
    },
    {
       "state":"North Carolina",
       "stateAbbr":"NC",
       "allArtists":[
          {
             "count":"59,805",
             "lq":"0.80"
          }
       ],
       "architects":[
          {
             "count":"3,905",
             "lq":"0.71"
          }
       ],
       "artDirectors":[
          {
             "count":"5,710",
             "lq":"0.79"
          }
       ],
       "designers":[
          {
             "count":"23,700",
             "lq":"0.82"
          }
       ],
       "dancers":[
          {
             "count":"430",
             "lq":"0.63"
          }
       ],
       "musicians":[
          {
             "count":"5,010",
             "lq":"0.96"
          }
       ],
       "actors":[
          {
             "count":"585",
             "lq":"0.31"
          }
       ],
       "entertainers":[
          {
             "count":"1,190",
             "lq":"0.78"
          }
       ],
       "writers":[
          {
             "count":"6,620",
             "lq":"0.86"
          }
       ],
       "photographers":[
          {
             "count":"5,125",
             "lq":"0.87"
          }
       ]
    },
    {
       "state":"New York",
       "stateAbbr":"NY",
       "allArtists":[
          {
             "count":"243,405",
             "lq":"1.66"
          }
       ],
       "architects":[
          {
             "count":"17,985",
             "lq":"1.66"
          }
       ],
       "artDirectors":[
          {
             "count":"24,315",
             "lq":"1.72"
          }
       ],
       "designers":[
          {
             "count":"85,980",
             "lq":"1.51"
          }
       ],
       "dancers":[
          {
             "count":"2,085",
             "lq":"1.55"
          }
       ],
       "musicians":[
          {
             "count":"14,245",
             "lq":"1.39"
          }
       ],
       "actors":[
          {
             "count":"11,320",
             "lq":"3.06"
          }
       ],
       "entertainers":[
          {
             "count":"4,260",
             "lq":"1.42"
          }
       ],
       "writers":[
          {
             "count":"27,765",
             "lq":"1.83"
          }
       ],
       "photographers":[
          {
             "count":"15,485",
             "lq":"1.34"
          }
       ]
    },
    {
       "state":"New Mexico",
       "stateAbbr":"NM",
       "allArtists":[
          {
             "count":"12,555",
             "lq":"0.90"
          }
       ],
       "architects":[
          {
             "count":"880",
             "lq":"0.85"
          }
       ],
       "artDirectors":[
          {
             "count":"2,405",
             "lq":"1.78"
          }
       ],
       "designers":[
          {
             "count":"3,805",
             "lq":"0.70"
          }
       ],
       "dancers":[
          {
             "count":"55",
             "lq":"0.43"
          }
       ],
       "musicians":[
          {
             "count":"800",
             "lq":"0.82"
          }
       ],
       "actors":[
          {
             "count":"325",
             "lq":"0.92"
          }
       ],
       "entertainers":[
          {
             "count":"175",
             "lq":"0.61"
          }
       ],
       "writers":[
          {
             "count":"1,480",
             "lq":"1.02"
          }
       ],
       "photographers":[
          {
             "count":"1,210",
             "lq":"1.10"
          }
       ]
    },
    {
       "state":"New Jersey",
       "stateAbbr":"NJ",
       "allArtists":[
          {
             "count":"70,265",
             "lq":"1.03"
          }
       ],
       "architects":[
          {
             "count":"5,990",
             "lq":"1.19"
          }
       ],
       "artDirectors":[
          {
             "count":"5,510",
             "lq":"0.84"
          }
       ],
       "designers":[
          {
             "count":"29,120",
             "lq":"1.10"
          }
       ],
       "dancers":[
          {
             "count":"710",
             "lq":"1.13"
          }
       ],
       "musicians":[
          {
             "count":"4,330",
             "lq":"0.91"
          }
       ],
       "actors":[
          {
             "count":"1,675",
             "lq":"0.97"
          }
       ],
       "entertainers":[
          {
             "count":"1,170",
             "lq":"0.84"
          }
       ],
       "writers":[
          {
             "count":"6,970",
             "lq":"0.99"
          }
       ],
       "photographers":[
          {
             "count":"5,210",
             "lq":"0.97"
          }
       ]
    },
    {
       "state":"New Hampshire",
       "stateAbbr":"NH",
       "allArtists":[
          {
             "count":"9,100",
             "lq":"0.82"
          }
       ],
       "architects":[
          {
             "count":"625",
             "lq":"0.77"
          }
       ],
       "artDirectors":[
          {
             "count":"870",
             "lq":"0.82"
          }
       ],
       "designers":[
          {
             "count":"4,565",
             "lq":"1.06"
          }
       ],
       "dancers":[
          {
             "count":"*",
             "lq":"*"
          }
       ],
       "musicians":[
          {
             "count":"450",
             "lq":"0.58"
          }
       ],
       "actors":[
          {
             "count":"110",
             "lq":"0.39"
          }
       ],
       "entertainers":[
          {
             "count":"60",
             "lq":"0.27"
          }
       ],
       "writers":[
          {
             "count":"985",
             "lq":"0.86"
          }
       ],
       "photographers":[
          {
             "count":"640",
             "lq":"0.74"
          }
       ]
    },
    {
       "state":"Nevada",
       "stateAbbr":"NV",
       "allArtists":[
          {
             "count":"23,665",
             "lq":"1.08"
          }
       ],
       "architects":[
          {
             "count":"570",
             "lq":"0.35"
          }
       ],
       "artDirectors":[
          {
             "count":"2,060",
             "lq":"0.97"
          }
       ],
       "designers":[
          {
             "count":"7,515",
             "lq":"0.88"
          }
       ],
       "dancers":[
          {
             "count":"1,105",
             "lq":"5.50"
          }
       ],
       "musicians":[
          {
             "count":"2,145",
             "lq":"1.40"
          }
       ],
       "actors":[
          {
             "count":"440",
             "lq":"0.79"
          }
       ],
       "entertainers":[
          {
             "count":"2,605",
             "lq":"5.81"
          }
       ],
       "writers":[
          {
             "count":"1,995",
             "lq":"0.88"
          }
       ],
       "photographers":[
          {
             "count":"2,210",
             "lq":"1.28"
          }
       ]
    },
    {
       "state":"Nebraska",
       "stateAbbr":"NE",
       "allArtists":[
          {
             "count":"10,875",
             "lq":"0.72"
          }
       ],
       "architects":[
          {
             "count":"760",
             "lq":"0.68"
          }
       ],
       "artDirectors":[
          {
             "count":"915",
             "lq":"0.63"
          }
       ],
       "designers":[
          {
             "count":"4,505",
             "lq":"0.77"
          }
       ],
       "dancers":[
          {
             "count":"120",
             "lq":"0.87"
          }
       ],
       "musicians":[
          {
             "count":"625",
             "lq":"0.59"
          }
       ],
       "actors":[
          {
             "count":"50",
             "lq":"0.13"
          }
       ],
       "entertainers":[
          {
             "count":"205",
             "lq":"0.66"
          }
       ],
       "writers":[
          {
             "count":"990",
             "lq":"0.63"
          }
       ],
       "photographers":[
          {
             "count":"955",
             "lq":"0.80"
          }
       ]
    },
    {
       "state":"Montana",
       "stateAbbr":"MT",
       "allArtists":[
          {
             "count":"6,910",
             "lq":"0.88"
          }
       ],
       "architects":[
          {
             "count":"520",
             "lq":"0.90"
          }
       ],
       "artDirectors":[
          {
             "count":"990",
             "lq":"1.31"
          }
       ],
       "designers":[
          {
             "count":"2,305",
             "lq":"0.76"
          }
       ],
       "dancers":[
          {
             "count":"85",
             "lq":"1.19"
          }
       ],
       "musicians":[
          {
             "count":"420",
             "lq":"0.77"
          }
       ],
       "actors":[
          {
             "count":"45",
             "lq":"0.23"
          }
       ],
       "entertainers":[
          {
             "count":"95",
             "lq":"0.59"
          }
       ],
       "writers":[
          {
             "count":"720",
             "lq":"0.89"
          }
       ],
       "photographers":[
          {
             "count":"770",
             "lq":"1.25"
          }
       ]
    },
    {
       "state":"Missouri",
       "stateAbbr":"MO",
       "allArtists":[
          {
             "count":"36,300",
             "lq":"0.81"
          }
       ],
       "architects":[
          {
             "count":"2,980",
             "lq":"0.90"
          }
       ],
       "artDirectors":[
          {
             "count":"3,050",
             "lq":"0.71"
          }
       ],
       "designers":[
          {
             "count":"15,525",
             "lq":"0.89"
          }
       ],
       "dancers":[
          {
             "count":"315",
             "lq":"0.77"
          }
       ],
       "musicians":[
          {
             "count":"2,485",
             "lq":"0.79"
          }
       ],
       "actors":[
          {
             "count":"415",
             "lq":"0.37"
          }
       ],
       "entertainers":[
          {
             "count":"850",
             "lq":"0.93"
          }
       ],
       "writers":[
          {
             "count":"3,320",
             "lq":"0.72"
          }
       ],
       "photographers":[
          {
             "count":"2,970",
             "lq":"0.84"
          }
       ]
    },
    {
       "state":"Mississippi",
       "stateAbbr":"MS",
       "allArtists":[
          {
             "count":"8,905",
             "lq":"0.45"
          }
       ],
       "architects":[
          {
             "count":"555",
             "lq":"0.38"
          }
       ],
       "artDirectors":[
          {
             "count":"715",
             "lq":"0.38"
          }
       ],
       "designers":[
          {
             "count":"3,285",
             "lq":"0.43"
          }
       ],
       "dancers":[
          {
             "count":"55",
             "lq":"0.31"
          }
       ],
       "musicians":[
          {
             "count":"1,060",
             "lq":"0.77"
          }
       ],
       "actors":[
          {
             "count":"35",
             "lq":"0.07"
          }
       ],
       "entertainers":[
          {
             "count":"25",
             "lq":"0.06"
          }
       ],
       "writers":[
          {
             "count":"625",
             "lq":"0.31"
          }
       ],
       "photographers":[
          {
             "count":"975",
             "lq":"0.63"
          }
       ]
    },
    {
       "state":"Minnesota",
       "stateAbbr":"MN",
       "allArtists":[
          {
             "count":"45,180",
             "lq":"1.01"
          }
       ],
       "architects":[
          {
             "count":"3,455",
             "lq":"1.05"
          }
       ],
       "artDirectors":[
          {
             "count":"4,240",
             "lq":"0.98"
          }
       ],
       "designers":[
          {
             "count":"20,145",
             "lq":"1.16"
          }
       ],
       "dancers":[
          {
             "count":"245",
             "lq":"0.60"
          }
       ],
       "musicians":[
          {
             "count":"2,700",
             "lq":"0.86"
          }
       ],
       "actors":[
          {
             "count":"545",
             "lq":"0.48"
          }
       ],
       "entertainers":[
          {
             "count":"570",
             "lq":"0.62"
          }
       ],
       "writers":[
          {
             "count":"4,900",
             "lq":"1.06"
          }
       ],
       "photographers":[
          {
             "count":"3,290",
             "lq":"0.93"
          }
       ]
    },
    {
       "state":"Michigan",
       "stateAbbr":"MI",
       "allArtists":[
          {
             "count":"61,020",
             "lq":"0.85"
          }
       ],
       "architects":[
          {
             "count":"3,000",
             "lq":"0.56"
          }
       ],
       "artDirectors":[
          {
             "count":"5,395",
             "lq":"0.77"
          }
       ],
       "designers":[
          {
             "count":"28,910",
             "lq":"1.03"
          }
       ],
       "dancers":[
          {
             "count":"460",
             "lq":"0.70"
          }
       ],
       "musicians":[
          {
             "count":"4,670",
             "lq":"0.93"
          }
       ],
       "actors":[
          {
             "count":"530",
             "lq":"0.29"
          }
       ],
       "entertainers":[
          {
             "count":"1,030",
             "lq":"0.70"
          }
       ],
       "writers":[
          {
             "count":"5,990",
             "lq":"0.80"
          }
       ],
       "photographers":[
          {
             "count":"4,720",
             "lq":"0.83"
          }
       ]
    },
    {
       "state":"Massachusetts",
       "stateAbbr":"MA",
       "allArtists":[
          {
             "count":"61,910",
             "lq":"1.12"
          }
       ],
       "architects":[
          {
             "count":"6,665",
             "lq":"1.63"
          }
       ],
       "artDirectors":[
          {
             "count":"5,775",
             "lq":"1.08"
          }
       ],
       "designers":[
          {
             "count":"25,210",
             "lq":"1.17"
          }
       ],
       "dancers":[
          {
             "count":"415",
             "lq":"0.82"
          }
       ],
       "musicians":[
          {
             "count":"3,565",
             "lq":"0.92"
          }
       ],
       "actors":[
          {
             "count":"665",
             "lq":"0.48"
          }
       ],
       "entertainers":[
          {
             "count":"820",
             "lq":"0.73"
          }
       ],
       "writers":[
          {
             "count":"8,230",
             "lq":"1.44"
          }
       ],
       "photographers":[
          {
             "count":"3,630",
             "lq":"0.83"
          }
       ]
    },
    {
       "state":"Maryland",
       "stateAbbr":"MD",
       "allArtists":[
          {
             "count":"46,680",
             "lq":"0.98"
          }
       ],
       "architects":[
          {
             "count":"4,635",
             "lq":"1.32"
          }
       ],
       "artDirectors":[
          {
             "count":"3,660",
             "lq":"0.80"
          }
       ],
       "designers":[
          {
             "count":"16,310",
             "lq":"0.88"
          }
       ],
       "dancers":[
          {
             "count":"515",
             "lq":"1.18"
          }
       ],
       "musicians":[
          {
             "count":"3,390",
             "lq":"1.02"
          }
       ],
       "actors":[
          {
             "count":"575",
             "lq":"0.48"
          }
       ],
       "entertainers":[
          {
             "count":"595",
             "lq":"0.61"
          }
       ],
       "writers":[
          {
             "count":"6,315",
             "lq":"1.28"
          }
       ],
       "photographers":[
          {
             "count":"3,715",
             "lq":"0.99"
          }
       ]
    },
    {
       "state":"Maine",
       "stateAbbr":"ME",
       "allArtists":[
          {
             "count":"9,065",
             "lq":"0.89"
          }
       ],
       "architects":[
          {
             "count":"465",
             "lq":"0.62"
          }
       ],
       "artDirectors":[
          {
             "count":"1,505",
             "lq":"1.53"
          }
       ],
       "designers":[
          {
             "count":"3,730",
             "lq":"0.94"
          }
       ],
       "dancers":[
          {
             "count":"215",
             "lq":"2.30"
          }
       ],
       "musicians":[
          {
             "count":"455",
             "lq":"0.64"
          }
       ],
       "actors":[
          {
             "count":"45",
             "lq":"0.17"
          }
       ],
       "entertainers":[
          {
             "count":"115",
             "lq":"0.55"
          }
       ],
       "writers":[
          {
             "count":"1,170",
             "lq":"1.11"
          }
       ],
       "photographers":[
          {
             "count":"590",
             "lq":"0.73"
          }
       ]
    },
    {
       "state":"Louisiana",
       "stateAbbr":"LA",
       "allArtists":[
          {
             "count":"25,350",
             "lq":"0.79"
          }
       ],
       "architects":[
          {
             "count":"1,615",
             "lq":"0.69"
          }
       ],
       "artDirectors":[
          {
             "count":"2,800",
             "lq":"0.91"
          }
       ],
       "designers":[
          {
             "count":"8,970",
             "lq":"0.72"
          }
       ],
       "dancers":[
          {
             "count":"375",
             "lq":"1.28"
          }
       ],
       "musicians":[
          {
             "count":"3,075",
             "lq":"1.38"
          }
       ],
       "actors":[
          {
             "count":"1,130",
             "lq":"1.40"
          }
       ],
       "entertainers":[
          {
             "count":"365",
             "lq":"0.56"
          }
       ],
       "writers":[
          {
             "count":"1,385",
             "lq":"0.42"
          }
       ],
       "photographers":[
          {
             "count":"2,120",
             "lq":"0.84"
          }
       ]
    },
    {
       "state":"Kentucky",
       "stateAbbr":"KY",
       "allArtists":[
          {
             "count":"18,535",
             "lq":"0.60"
          }
       ],
       "architects":[
          {
             "count":"1,055",
             "lq":"0.47"
          }
       ],
       "artDirectors":[
          {
             "count":"1,855",
             "lq":"0.63"
          }
       ],
       "designers":[
          {
             "count":"7,655",
             "lq":"0.64"
          }
       ],
       "dancers":[
          {
             "count":"135",
             "lq":"0.48"
          }
       ],
       "musicians":[
          {
             "count":"1,395",
             "lq":"0.65"
          }
       ],
       "actors":[
          {
             "count":"260",
             "lq":"0.34"
          }
       ],
       "entertainers":[
          {
             "count":"285",
             "lq":"0.45"
          }
       ],
       "writers":[
          {
             "count":"1,620",
             "lq":"0.51"
          }
       ],
       "photographers":[
          {
             "count":"1,760",
             "lq":"0.73"
          }
       ]
    },
    {
       "state":"Kansas",
       "stateAbbr":"KS",
       "allArtists":[
          {
             "count":"17,295",
             "lq":"0.78"
          }
       ],
       "architects":[
          {
             "count":"1,745",
             "lq":"1.07"
          }
       ],
       "artDirectors":[
          {
             "count":"1,445",
             "lq":"0.68"
          }
       ],
       "designers":[
          {
             "count":"7,415",
             "lq":"0.86"
          }
       ],
       "dancers":[
          {
             "count":"125",
             "lq":"0.62"
          }
       ],
       "musicians":[
          {
             "count":"1,235",
             "lq":"0.80"
          }
       ],
       "actors":[
          {
             "count":"50",
             "lq":"0.09"
          }
       ],
       "entertainers":[
          {
             "count":"245",
             "lq":"0.54"
          }
       ],
       "writers":[
          {
             "count":"2,060",
             "lq":"0.90"
          }
       ],
       "photographers":[
          {
             "count":"1,345",
             "lq":"0.77"
          }
       ]
    },
    {
       "state":"Iowa",
       "stateAbbr":"IA",
       "allArtists":[
          {
             "count":"15,735",
             "lq":"0.64"
          }
       ],
       "architects":[
          {
             "count":"905",
             "lq":"0.50"
          }
       ],
       "artDirectors":[
          {
             "count":"1,220",
             "lq":"0.52"
          }
       ],
       "designers":[
          {
             "count":"6,965",
             "lq":"0.73"
          }
       ],
       "dancers":[
          {
             "count":"105",
             "lq":"0.47"
          }
       ],
       "musicians":[
          {
             "count":"940",
             "lq":"0.55"
          }
       ],
       "actors":[
          {
             "count":"65",
             "lq":"0.11"
          }
       ],
       "entertainers":[
          {
             "count":"95",
             "lq":"0.19"
          }
       ],
       "writers":[
          {
             "count":"1,835",
             "lq":"0.73"
          }
       ],
       "photographers":[
          {
             "count":"1,665",
             "lq":"0.87"
          }
       ]
    },
    {
       "state":"Indiana",
       "stateAbbr":"IN",
       "allArtists":[
          {
             "count":"31,585",
             "lq":"0.64"
          }
       ],
       "architects":[
          {
             "count":"1,345",
             "lq":"0.37"
          }
       ],
       "artDirectors":[
          {
             "count":"2,910",
             "lq":"0.61"
          }
       ],
       "designers":[
          {
             "count":"14,580",
             "lq":"0.77"
          }
       ],
       "dancers":[
          {
             "count":"160",
             "lq":"0.36"
          }
       ],
       "musicians":[
          {
             "count":"2,450",
             "lq":"0.71"
          }
       ],
       "actors":[
          {
             "count":"325",
             "lq":"0.26"
          }
       ],
       "entertainers":[
          {
             "count":"405",
             "lq":"0.40"
          }
       ],
       "writers":[
          {
             "count":"3,025",
             "lq":"0.60"
          }
       ],
       "photographers":[
          {
             "count":"2,990",
             "lq":"0.77"
          }
       ]
    },
    {
       "state":"Illinois",
       "stateAbbr":"IL",
       "allArtists":[
          {
             "count":"89,425",
             "lq":"0.92"
          }
       ],
       "architects":[
          {
             "count":"8,770",
             "lq":"1.23"
          }
       ],
       "artDirectors":[
          {
             "count":"7,165",
             "lq":"0.76"
          }
       ],
       "designers":[
          {
             "count":"36,460",
             "lq":"0.97"
          }
       ],
       "dancers":[
          {
             "count":"635",
             "lq":"0.71"
          }
       ],
       "musicians":[
          {
             "count":"5,625",
             "lq":"0.83"
          }
       ],
       "actors":[
          {
             "count":"1,980",
             "lq":"0.81"
          }
       ],
       "entertainers":[
          {
             "count":"1,805",
             "lq":"0.91"
          }
       ],
       "writers":[
          {
             "count":"9,520",
             "lq":"0.95"
          }
       ],
       "photographers":[
          {
             "count":"6,770",
             "lq":"0.89"
          }
       ]
    },
    {
       "state":"Idaho",
       "stateAbbr":"ID",
       "allArtists":[
          {
             "count":"8,970",
             "lq":"0.74"
          }
       ],
       "architects":[
          {
             "count":"930",
             "lq":"1.04"
          }
       ],
       "artDirectors":[
          {
             "count":"925",
             "lq":"0.79"
          }
       ],
       "designers":[
          {
             "count":"4,170",
             "lq":"0.89"
          }
       ],
       "dancers":[
          {
             "count":"25",
             "lq":"0.23"
          }
       ],
       "musicians":[
          {
             "count":"385",
             "lq":"0.45"
          }
       ],
       "actors":[
          {
             "count":"60",
             "lq":"0.20"
          }
       ],
       "entertainers":[
          {
             "count":"105",
             "lq":"0.42"
          }
       ],
       "writers":[
          {
             "count":"935",
             "lq":"0.75"
          }
       ],
       "photographers":[
          {
             "count":"680",
             "lq":"0.71"
          }
       ]
    },
    {
       "state":"Hawaii",
       "stateAbbr":"HI",
       "allArtists":[
          {
             "count":"11,905",
             "lq":"1.09"
          }
       ],
       "architects":[
          {
             "count":"1,215",
             "lq":"1.50"
          }
       ],
       "artDirectors":[
          {
             "count":"1,450",
             "lq":"1.37"
          }
       ],
       "designers":[
          {
             "count":"3,345",
             "lq":"0.79"
          }
       ],
       "dancers":[
          {
             "count":"355",
             "lq":"3.54"
          }
       ],
       "musicians":[
          {
             "count":"1,265",
             "lq":"1.65"
          }
       ],
       "actors":[
          {
             "count":"105",
             "lq":"0.38"
          }
       ],
       "entertainers":[
          {
             "count":"305",
             "lq":"1.36"
          }
       ],
       "writers":[
          {
             "count":"790",
             "lq":"0.70"
          }
       ],
       "photographers":[
          {
             "count":"1,615",
             "lq":"1.87"
          }
       ]
    },
    {
       "state":"Georgia",
       "stateAbbr":"GA",
       "allArtists":[
          {
             "count":"67,265",
             "lq":"0.89"
          }
       ],
       "architects":[
          {
             "count":"5,305",
             "lq":"0.95"
          }
       ],
       "artDirectors":[
          {
             "count":"5,955",
             "lq":"0.82"
          }
       ],
       "designers":[
          {
             "count":"24,625",
             "lq":"0.84"
          }
       ],
       "dancers":[
          {
             "count":"1,015",
             "lq":"1.47"
          }
       ],
       "musicians":[
          {
             "count":"5,400",
             "lq":"1.03"
          }
       ],
       "actors":[
          {
             "count":"2,465",
             "lq":"1.30"
          }
       ],
       "entertainers":[
          {
             "count":"1,675",
             "lq":"1.09"
          }
       ],
       "writers":[
          {
             "count":"4,970",
             "lq":"0.64"
          }
       ],
       "photographers":[
          {
             "count":"6,180",
             "lq":"1.04"
          }
       ]
    },
    {
       "state":"Florida",
       "stateAbbr":"FL",
       "allArtists":[
          {
             "count":"139,495",
             "lq":"0.95"
          }
       ],
       "architects":[
          {
             "count":"9,200",
             "lq":"0.85"
          }
       ],
       "artDirectors":[
          {
             "count":"14,240",
             "lq":"1.00"
          }
       ],
       "designers":[
          {
             "count":"51,620",
             "lq":"0.90"
          }
       ],
       "dancers":[
          {
             "count":"1,545",
             "lq":"1.14"
          }
       ],
       "musicians":[
          {
             "count":"10,960",
             "lq":"1.06"
          }
       ],
       "actors":[
          {
             "count":"2,805",
             "lq":"0.75"
          }
       ],
       "entertainers":[
          {
             "count":"7,095",
             "lq":"2.36"
          }
       ],
       "writers":[
          {
             "count":"11,125",
             "lq":"0.73"
          }
       ],
       "photographers":[
          {
             "count":"12,840",
             "lq":"1.11"
          }
       ]
    },
    {
       "state":"District of Columbia",
       "stateAbbr":"DC",
       "allArtists":[
          {
             "count":"12,355",
             "lq":"2.08"
          }
       ],
       "architects":[
          {
             "count":"1,245",
             "lq":"2.84"
          }
       ],
       "artDirectors":[
          {
             "count":"1,035",
             "lq":"1.80"
          }
       ],
       "designers":[
          {
             "count":"3,050",
             "lq":"1.32"
          }
       ],
       "dancers":[
          {
             "count":"75",
             "lq":"1.38"
          }
       ],
       "musicians":[
          {
             "count":"430",
             "lq":"1.04"
          }
       ],
       "actors":[
          {
             "count":"215",
             "lq":"1.43"
          }
       ],
       "entertainers":[
          {
             "count":"65",
             "lq":"0.54"
          }
       ],
       "writers":[
          {
             "count":"3,440",
             "lq":"5.60"
          }
       ],
       "photographers":[
          {
             "count":"540",
             "lq":"1.16"
          }
       ]
    },
    {
       "state":"Delaware",
       "stateAbbr":"DE",
       "allArtists":[
          {
             "count":"4,780",
             "lq":"0.68"
          }
       ],
       "architects":[
          {
             "count":"280",
             "lq":"0.54"
          }
       ],
       "artDirectors":[
          {
             "count":"380",
             "lq":"0.56"
          }
       ],
       "designers":[
          {
             "count":"2,100",
             "lq":"0.77"
          }
       ],
       "dancers":[
          {
             "count":"45",
             "lq":"0.69"
          }
       ],
       "musicians":[
          {
             "count":"345",
             "lq":"0.70"
          }
       ],
       "actors":[
          {
             "count":"55",
             "lq":"0.31"
          }
       ],
       "entertainers":[
          {
             "count":"70",
             "lq":"0.48"
          }
       ],
       "writers":[
          {
             "count":"390",
             "lq":"0.53"
          }
       ],
       "photographers":[
          {
             "count":"375",
             "lq":"0.67"
          }
       ]
    },
    {
       "state":"Connecticut",
       "stateAbbr":"CT",
       "allArtists":[
          {
             "count":"29,925",
             "lq":"1.06"
          }
       ],
       "architects":[
          {
             "count":"2,990",
             "lq":"1.43"
          }
       ],
       "artDirectors":[
          {
             "count":"2,640",
             "lq":"0.97"
          }
       ],
       "designers":[
          {
             "count":"11,625",
             "lq":"1.06"
          }
       ],
       "dancers":[
          {
             "count":"95",
             "lq":"0.37"
          }
       ],
       "musicians":[
          {
             "count":"1,820",
             "lq":"0.92"
          }
       ],
       "actors":[
          {
             "count":"515",
             "lq":"0.72"
          }
       ],
       "entertainers":[
          {
             "count":"240",
             "lq":"0.42"
          }
       ],
       "writers":[
          {
             "count":"2,785",
             "lq":"0.95"
          }
       ],
       "photographers":[
          {
             "count":"1,985",
             "lq":"0.89"
          }
       ]
    },
    {
       "state":"Colorado",
       "stateAbbr":"CO",
       "allArtists":[
          {
             "count":"50,860",
             "lq":"1.14"
          }
       ],
       "architects":[
          {
             "count":"5,345",
             "lq":"1.62"
          }
       ],
       "artDirectors":[
          {
             "count":"4,540",
             "lq":"1.05"
          }
       ],
       "designers":[
          {
             "count":"20,120",
             "lq":"1.16"
          }
       ],
       "dancers":[
          {
             "count":"375",
             "lq":"0.92"
          }
       ],
       "musicians":[
          {
             "count":"2,850",
             "lq":"0.91"
          }
       ],
       "actors":[
          {
             "count":"505",
             "lq":"0.45"
          }
       ],
       "entertainers":[
          {
             "count":"970",
             "lq":"1.06"
          }
       ],
       "writers":[
          {
             "count":"6,105",
             "lq":"1.32"
          }
       ],
       "photographers":[
          {
             "count":"4,335",
             "lq":"1.23"
          }
       ]
    },
    {
       "state":"California",
       "stateAbbr":"CA",
       "allArtists":[
          {
             "count":"445,095",
             "lq":"1.53"
          }
       ],
       "architects":[
          {
             "count":"26,760",
             "lq":"1.25"
          }
       ],
       "artDirectors":[
          {
             "count":"45,870",
             "lq":"1.64"
          }
       ],
       "designers":[
          {
             "count":"159,535",
             "lq":"1.42"
          }
       ],
       "dancers":[
          {
             "count":"3,380",
             "lq":"1.27"
          }
       ],
       "musicians":[
          {
             "count":"26,205",
             "lq":"1.29"
          }
       ],
       "actors":[
          {
             "count":"24,140",
             "lq":"3.29"
          }
       ],
       "entertainers":[
          {
             "count":"10,265",
             "lq":"1.73"
          }
       ],
       "writers":[
          {
             "count":"45,625",
             "lq":"1.52"
          }
       ],
       "photographers":[
          {
             "count":"30,245",
             "lq":"1.32"
          }
       ]
    },
    {
       "state":"Arkansas",
       "stateAbbr":"AR",
       "allArtists":[
          {
             "count":"12,075",
             "lq":"0.60"
          }
       ],
       "architects":[
          {
             "count":"465",
             "lq":"0.31"
          }
       ],
       "artDirectors":[
          {
             "count":"990",
             "lq":"0.51"
          }
       ],
       "designers":[
          {
             "count":"5,295",
             "lq":"0.68"
          }
       ],
       "dancers":[
          {
             "count":"105",
             "lq":"0.57"
          }
       ],
       "musicians":[
          {
             "count":"950",
             "lq":"0.68"
          }
       ],
       "actors":[
          {
             "count":"*",
             "lq":"*"
          }
       ],
       "entertainers":[
          {
             "count":"155",
             "lq":"0"
          }
       ],
       "writers":[
          {
             "count":"1,130",
             "lq":"0.54"
          }
       ],
       "photographers":[
          {
             "count":"1,460",
             "lq":"0.92"
          }
       ]
    },
    {
       "state":"Arizona",
       "stateAbbr":"AZ",
       "allArtists":[
          {
             "count":"41,960",
             "lq":"0.86"
          }
       ],
       "architects":[
          {
             "count":"3,145",
             "lq":"0.88"
          }
       ],
       "artDirectors":[
          {
             "count":"4,575",
             "lq":"0.97"
          }
       ],
       "designers":[
          {
             "count":"16,645",
             "lq":"0.88"
          }
       ],
       "dancers":[
          {
             "count":"635",
             "lq":"1.42"
          }
       ],
       "musicians":[
          {
             "count":"2,735",
             "lq":"0.80"
          }
       ],
       "actors":[
          {
             "count":"635",
             "lq":"0.52"
          }
       ],
       "entertainers":[
          {
             "count":"850",
             "lq":"0.85"
          }
       ],
       "writers":[
          {
             "count":"4,070",
             "lq":"0.81"
          }
       ],
       "photographers":[
          {
             "count":"3,725",
             "lq":"0.97"
          }
       ]
    },
    {
       "state":"Alaska",
       "stateAbbr":"AK",
       "allArtists":[
          {
             "count":"3,790",
             "lq":"0.66"
          }
       ],
       "architects":[
          {
             "count":"280",
             "lq":"0.66"
          }
       ],
       "artDirectors":[
          {
             "count":"715",
             "lq":"1.30"
          }
       ],
       "designers":[
          {
             "count":"1,025",
             "lq":"0.46"
          }
       ],
       "dancers":[
          {
             "count":"30",
             "lq":"0.57"
          }
       ],
       "musicians":[
          {
             "count":"100",
             "lq":"0.25"
          }
       ],
       "actors":[
          {
             "count":"70",
             "lq":"0.49"
          }
       ],
       "entertainers":[
          {
             "count":"80",
             "lq":"0.69"
          }
       ],
       "writers":[
          {
             "count":"510",
             "lq":"0.86"
          }
       ],
       "photographers":[
          {
             "count":"510",
             "lq":"1.13"
          }
       ]
    },
    {
       "state":"Alabama",
       "stateAbbr":"AL",
       "allArtists":[
          {
             "count":"20,350",
             "lq":"0.62"
          }
       ],
       "architects":[
          {
             "count":"1,065",
             "lq":"0.44"
          }
       ],
       "artDirectors":[
          {
             "count":"1,505",
             "lq":"0.48"
          }
       ],
       "designers":[
          {
             "count":"7,805",
             "lq":"0.62"
          }
       ],
       "dancers":[
          {
             "count":"165",
             "lq":"0.55"
          }
       ],
       "musicians":[
          {
             "count":"2,080",
             "lq":"0.91"
          }
       ],
       "actors":[
          {
             "count":"195",
             "lq":"0.24"
          }
       ],
       "entertainers":[
          {
             "count":"425",
             "lq":"0.64"
          }
       ],
       "writers":[
          {
             "count":"1,960",
             "lq":"0.58"
          }
       ],
       "photographers":[
          {
             "count":"1,880",
             "lq":"0.73"
          }
       ]
    },
    {
       "state":"United States",
       "stateAbbr":"US",
       "allArtists":[
          {
             "count":"2,398,305",
             "lq":""
          }
       ],
       "architects":[
          {
             "count":"176,800",
             "lq":""
          }
       ],
       "artDirectors":[
          {
             "count":"231,490",
             "lq":""
          }
       ],
       "designers":[
          {
             "count":"930,625",
             "lq":""
          }
       ],
       "dancers":[
          {
             "count":"21,960",
             "lq":""
          }
       ],
       "musicians":[
          {
             "count":"167,580",
             "lq":""
          }
       ],
       "actors":[
          {
             "count":"60,545",
             "lq":""
          }
       ],
       "entertainers":[
          {
             "count":"48,975",
             "lq":""
          }
       ],
       "writers":[
          {
             "count":"247,995",
             "lq":""
          }
       ],
       "photographers":[
          {
             "count":"188,690",
             "lq":""
          }
       ]
    }
 ]